name: Build React App

on:
  push:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: comamnd line
        run: ls -la
      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
